import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Web3Modal from "web3modal"
import { ethers } from "ethers"
import WalletConnectProvider from "@walletconnect/web3-provider"

let web3Modal;

const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider,
    options: {
      infuraId: process.NEXT_PUBLIC_INFURA_KEY,
    }
  }
}

if (typeof window !== "undefined") {
  web3Modal = new Web3Modal({
    cacheProvider: false,
    providerOptions, // required
  });
}

export default function Home() {
  const [state, setState] = useState({
    isWalletConnected: false,
    walletAddress: null,
    provider: null,
    signer: null,
  })


  async function showWeb3Modal() {
    try {
      const web3ModalProvider = await web3Modal.connect()
      const _provider = new ethers.providers.Web3Provider(web3ModalProvider)
      const _signer = _provider.getSigner()
      const _walletAddress = await _signer.getAddress()

      setState({
        provider: _provider, 
        signer: _signer, 
        walletAddress: _walletAddress, 
        isWalletConnected: true})

    } catch (e) {
      console.log(e)
    }
  }

  // async function showWeb3Modal() {
  //   if (!state.instance) {
  //     const web3Modal = new Web3Modal({
  //       cacheProvider: true, // optional
  //       providerOptions // required
  //     })

  //     try {
  //       const _instance = await web3Modal.connect()
  //       const _provider = new ethers.providers.Web3Provider(_instance)
  //       const _signer = _provider.getSigner()
  //       const _walletAddress = await _signer.getAddress()

  //       setState({
  //         instance: _instance, 
  //         provider: _provider, 
  //         signer: _signer, 
  //         walletAddress: _walletAddress, 
  //         isWalletConnected: true})

  //     } catch (error) {
  //       console.log(error)
  //     }
  //   }
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        💧 👁 🔥
        </h1>

        { state.isWalletConnected ? (

          <a>{state.walletAddress}</a>

        ) : (

          <p className={styles.description}>
            <a href="#" className={styles.button_anon_pen} onClick={() => showWeb3Modal()}>
              <span>Connect Wallet</span>
            </a>
          </p>

        )}
      </main>

      <footer className={styles.footer}>
        🙌🏼
      </footer>
    </div>
  )
}
